# Generated by Django 3.2 on 2022-05-28 18:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drill_types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drill_type', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Drill types',
                'db_table': 'training_drill_types',
            },
        ),
        migrations.CreateModel(
            name='Drills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('score_type', models.IntegerField()),
                ('has_test', models.BooleanField()),
                ('time_bound', models.BooleanField()),
                ('test_duration', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('drill_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.drill_types')),
            ],
            options={
                'verbose_name_plural': 'Drills',
                'db_table': 'training_drills',
            },
        ),
        migrations.CreateModel(
            name='Training_sessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.IntegerField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('drill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.drills')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Training sessions',
                'db_table': 'training_sessions',
            },
        ),
    ]
